### ISSUE TITLE
Code Improvements

### ISSUE THREAD

**Issue by MC2BP** [MasterEvarior/cocopasty#6]
Did a code review of your backend, found some things that should be improved.

**In General**
* All your methods are currently private. Change the util and database function to public (by capitalization of the 1. letter).
* Most of your logs are useless. They describe the working operations which don't benefit the debugging process. In readEntry() for example you log `Getting value from Redis...` and if it fails you log the error. Why not log `Failed to get value from Redis: <error>`. That way you know where it failed. 
* Also for error handling you might want to look into an error library. 
Shameless self promotion: I'm currently writing a framework with it's own errorlibrary, where the errors print the stacktrace. The idea behind it is to just return the errors until they are handled or just logged, where you know the source of it. 

**main.go**
* line 14: json tag incorrectly set, should be `json:"Code"`
* line 38 & 66: Implement middleware to log all requests
* line 40: Checking the Content-Type in every request manually is a bad approach. Better to write a middleware that checks if the Content-Type header is accurate and then expect the content it the correct format in the handlerfunc. 
* line 49: Since json.NewDecoder doesn't return an error you could combine it with the next line: `err := json.NewDecoder(r.Body).Decode(&newSnippet)`
* line 53: Why are you logging that it couldn't parse the json, and then print (not even println) the error? It would be better to send the error back `fmt.Fprintf(err.Error)`
* line 61 & 79: like 38 & 66 write a middleware for it
* line 62: this line is unnecessary, default is 200

**database.go**
line 11: You can combine your var declarations like this:
```golang
var (
	connection *redis.Client
	ctx        context.Context
)
```
* line 12: don't use global context, instead get it from the requests `r.Context()` and pass it on
* line 30: don't check if connection is nil on every call. Instead create a function called `init` which will be executed at startup and set the connection then. 
* line 35: connection.Set does NOT return an `error` and the handling and logging is incorrect. I'm unfamiliar with the redis library you're using, but from the looks of it you get the error by calling the `Err` method. 
* line 43: if a function can fail, then it should return an error and not just a bool. This way the error is passed on and can be properly handled. 

**util.go**
* line 14: in general you check if you have an error and then handle it, or return early. So it's better to replace line 15 with return and put `log.SetLevel(parsedLevel)` after the if. If you still want to print out the current loglevel you should put the log at the start with `defer` (defer executes the code after it when the functions is exited, so after return).

**go.mod**
* line 1: set the module properly `github.com/MasterEvariour/cocopasty/cocopasty-backend`. I'm unsure of how well this works, as go uses git tags for versioning of the project. I recommend having the front and backend in separate repositories.

**Comment by MasterEvarior** [comment]
Thanks, I implemented it with your help 😃 
Just gonna test it and then set it live (if it works)^^
